/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BecomeAConsultantRouteImport } from './routes/become-a-consultant'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesTransportRouteImport } from './routes/services.transport'
import { Route as ServicesEducationRouteImport } from './routes/services.education'
import { Route as ServicesConstructionRouteImport } from './routes/services.construction'
import { Route as ServicesAgricultureRouteImport } from './routes/services.agriculture'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAConsultantRoute = BecomeAConsultantRouteImport.update({
  id: '/become-a-consultant',
  path: '/become-a-consultant',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesTransportRoute = ServicesTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEducationRoute = ServicesEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesConstructionRoute = ServicesConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAgricultureRoute = ServicesAgricultureRouteImport.update({
  id: '/agriculture',
  path: '/agriculture',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-consultant': typeof BecomeAConsultantRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRouteWithChildren
  '/team': typeof TeamRoute
  '/services/agriculture': typeof ServicesAgricultureRoute
  '/services/construction': typeof ServicesConstructionRoute
  '/services/education': typeof ServicesEducationRoute
  '/services/transport': typeof ServicesTransportRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-consultant': typeof BecomeAConsultantRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/team': typeof TeamRoute
  '/services/agriculture': typeof ServicesAgricultureRoute
  '/services/construction': typeof ServicesConstructionRoute
  '/services/education': typeof ServicesEducationRoute
  '/services/transport': typeof ServicesTransportRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-consultant': typeof BecomeAConsultantRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRouteWithChildren
  '/team': typeof TeamRoute
  '/services/agriculture': typeof ServicesAgricultureRoute
  '/services/construction': typeof ServicesConstructionRoute
  '/services/education': typeof ServicesEducationRoute
  '/services/transport': typeof ServicesTransportRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-a-consultant'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/services'
    | '/team'
    | '/services/agriculture'
    | '/services/construction'
    | '/services/education'
    | '/services/transport'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-a-consultant'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/team'
    | '/services/agriculture'
    | '/services/construction'
    | '/services/education'
    | '/services/transport'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-a-consultant'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/services'
    | '/team'
    | '/services/agriculture'
    | '/services/construction'
    | '/services/education'
    | '/services/transport'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BecomeAConsultantRoute: typeof BecomeAConsultantRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-consultant': {
      id: '/become-a-consultant'
      path: '/become-a-consultant'
      fullPath: '/become-a-consultant'
      preLoaderRoute: typeof BecomeAConsultantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/transport': {
      id: '/services/transport'
      path: '/transport'
      fullPath: '/services/transport'
      preLoaderRoute: typeof ServicesTransportRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/education': {
      id: '/services/education'
      path: '/education'
      fullPath: '/services/education'
      preLoaderRoute: typeof ServicesEducationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/construction': {
      id: '/services/construction'
      path: '/construction'
      fullPath: '/services/construction'
      preLoaderRoute: typeof ServicesConstructionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/agriculture': {
      id: '/services/agriculture'
      path: '/agriculture'
      fullPath: '/services/agriculture'
      preLoaderRoute: typeof ServicesAgricultureRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAgricultureRoute: typeof ServicesAgricultureRoute
  ServicesConstructionRoute: typeof ServicesConstructionRoute
  ServicesEducationRoute: typeof ServicesEducationRoute
  ServicesTransportRoute: typeof ServicesTransportRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAgricultureRoute: ServicesAgricultureRoute,
  ServicesConstructionRoute: ServicesConstructionRoute,
  ServicesEducationRoute: ServicesEducationRoute,
  ServicesTransportRoute: ServicesTransportRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BecomeAConsultantRoute: BecomeAConsultantRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
